[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_SUPABASE_URL = "https://phcqdnzuicgmlhkmnpxc.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoY3Fkbnp1aWNnbWxoa21ucHhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjYyMzgsImV4cCI6MjA1OTcwMjIzOH0.1k7T17BSx7lvIcOLG2_qxNXpcb7FpvvoEkJUO97_HYI"
  VITE_GOOGLE_MAPS_API_KEY = ""
  STRIPE_SECRET_KEY = "sk_test_51PoZUCBf2yTNcRUo1QV8kTiBasytVelePrLdEchzzQJp1odHA4FmL9RA0Aq24OM9CLT8k2CdrrQirwAphQsEgXe600U7I5pYg1"